# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true


## Environment Properties

# The Minecraft version.
java_version_range=>=21
minecraft_version=1.21.6
minecraft_version_tag=1.21.6
minecraft_version_range=~1.21.6

# Fabric versions.
fabric_version=0.128.2+1.21.6
fabric_version_min=0.128.0
loader_version=0.16.14
loader_version_range=>=0.16
yarn_mappings=1.21.6+build.1
