#!/bin/bash
#
# This script regenerates "examples/prometheus_exporter.cfg".
#

# Exit on error.
set -e

# Get project directory.
home_dir="$(cd "$(dirname "$0")" && pwd)"

# Copy generated config from run.
out_file="$home_dir/examples/prometheus_exporter.cfg"
cp "$home_dir/prometheus_exporter.in.cfg" "$out_file"
echo '' >> "$out_file"
cat "$home_dir/run/config/prometheus_exporter.cfg" >> "$out_file"
cat "$out_file"
